In [1]:
import numpy as np

由于 NumPy 的主要数据类型是整数型数组或浮点型数组，因此布尔型数组
的产生离不开：大于>、大于等于>=、等于==、不等号!=、小于<、小于等于<=

In [2]:
# 创建数组
arr = np.arange(1, 7).reshape(2, 3)
print(arr)

# 数组与数字作比较
print(arr >= 4)

[[1 2 3]
 [4 5 6]]
[[False False False]
 [ True  True  True]]


In [4]:
# 创建同维数组
arr1 = np.arange(1, 6)
arr2 = np.flipud(arr1)
print(arr1)
print(arr2)

# 同维度数组作比较
print(arr1 > arr2)

[1 2 3 4 5]
[5 4 3 2 1]
[False False False  True  True]


最后，还可以同时比较多个条件。Python 基础里，同时检查多个条件使用的
与、或、非是 and、or、not。但 NumPy 中使用的与、或、非是 & 、 | 、～

In [5]:
# 创建数组
arr = np.arange(1, 10)
print(arr)

# 多个条件
print((arr < 4) | (arr > 6))

[1 2 3 4 5 6 7 8 9]
[ True  True  True False False False  True  True  True]


np.sum( )函数：统计布尔型数组里 True 的个数

In [6]:
# 创建一个形状为 10000 的标准正态分布数组
arr = np.random.normal(0, 1, 10000)
print(arr)

[-1.18851733 -0.83556726 -0.88744548 ...  0.28438908  1.17928925
  0.34125736]


In [7]:
# 统计该分布中绝对值小于 1 的元素个数
num = np.sum(np.abs(arr) < 1)
print(num)

6801


np.any( )函数： 只要布尔型数组里含有一个及其以上的 True， 就返回 True

In [8]:
# 创建同维数组
arr1 = np.arange(1, 10)
arr2 = np.flipud(arr1)
print(arr1)
print(arr2)

[1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1]


In [9]:
 # 统计这两个数组里是否有共同元素
print(np.any(arr1 == arr2))

True


np.all( )函数：当布尔型数组里全是 True 时，才返回 True

In [11]:
# 模拟英语六级的成绩，创建 100000 个样本
arr = np.random.normal(500, 70, 100000)
print(arr)

[410.00149165 540.62431446 532.80297398 ... 582.61395246 546.31775183
 504.08624142]


In [13]:
# 判断是否所有考生的分数都高于 250
print(np.all(arr > 250))

False


若一个普通数组和一个布尔型数组的维度相同，可以将布尔型数组作为普通
数组的掩码，这样可以对普通数组中的元素作筛选
掩码的工作原理：
- 当一个布尔型数组与一个普通数组具有相同的形状时，布尔型数组中的每个元素（True 或 False）会对应普通数组中的相应元素。
- 如果布尔数组中的某个元素是 True，那么普通数组中相应位置的元素会被保留；如果布尔数组中的某个元素是 False，那么普通数组中相应位置的元素会被丢弃。

In [14]:
# 创建数组
arr = np.arange(1, 13).reshape(3, 4)
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [15]:
# 数组与数字作比较
print(arr > 4)

[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


In [16]:
# 筛选出 arr > 4 的元素
print(arr[arr > 4])

[ 5  6  7  8  9 10 11 12]


In [17]:
# 创建同维数组
arr1 = np.arange(1, 10)
arr2 = np.flipud(arr1)
print(arr1)
print(arr2)

# 同维度数组作比较
print(arr1 > arr2)

[1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1]
[False False False False False  True  True  True  True]


In [18]:
# 筛选出 arr1 > arr2 位置上的元素
print(arr1[arr1 > arr2])
print(arr2[arr1 > arr2])

[6 7 8 9]
[4 3 2 1]


In [19]:
# 模拟英语六级成绩的随机数组，取 10000 个样本
arr = np.random.normal(500, 70, 1000)

In [20]:
# 找出六级成绩超过 650 的元素所在位置
print(np.where(arr > 650))

(array([164, 176, 273, 467, 486, 518, 796]),)


In [21]:
# 找出六级成绩最高分的元素所在位置
print(np.where(arr == np.max(arr)))

(array([796]),)
