In [1]:
import numpy as np

In [3]:
# 创建整型数组
arr1 = np.array([1, 2, 3])
print(arr1)

[1 2 3]


In [4]:
# 参加浮点型数组
arr2 = np.array([1.9, 2, 3])
print(arr2)

[1.9 2.  3. ]


In [9]:
# 整数型数组
arr1 = np.array([1, 2, 3])
arr1[0] = 100.9  # 插入浮点数，被截断，数组仍为整数型
print(arr1)

[100   2   3]


In [7]:
# 浮点型数组
arr2 = np.array([1.0, 2, 3])
arr2[1] = 10  # 插入整数型，被升级，数组仍为浮点型
print(arr2)

[ 1. 10.  3.]


In [11]:
# 整数型数组
arr1 = np.array([1, 2, 3])
print(arr1)

# 整数型数组 ——> 浮点型数组
arr2 = arr1.astype(float)
print(arr2)

# 浮点型数组 ——> 整数型数组
arr3 = arr2.astype(int)
print(arr3)

[1 2 3]
[1. 2. 3.]
[1 2 3]


In [13]:
# 整数型数组
arr = np.array([1, 2, 3])
print(arr)

# 整数型数组与浮点数做运算
print(arr + 0.0)
print(arr * 1.0)

# 整数型数组遇到除法（即便是除以整数）
print(arr / 1)

# 整数型数组与浮点型数组做运算
int_arr = np.array([1, 2, 3])
float_arr = np.array([1.0, 2, 3])
print(int_arr + float_arr)

[1 2 3]
[1. 2. 3.]
[1. 2. 3.]
[1. 2. 3.]
[2. 4. 6.]


In [15]:
arr1 = np.ones(3)  # 传入形状 3
print(arr1)  # 造出一维数组

[1. 1. 1.]


In [16]:
arr2 = np.ones((1, 3))  # 传入形状(1,3)
print(arr2)  # 造出二维数组

[[1. 1. 1.]]


In [17]:
arr3 = np.ones((1, 1, 3))  # 传入形状(1,1,3)
print(arr3)  # 造出三维数组

[[[1. 1. 1.]]]


In [18]:
print(arr1.shape)
print(arr2.shape)
print(arr3.shape)

(3,)
(1, 3)
(1, 1, 3)


In [19]:
# 创建一维数组
arr1 = np.arange(10)
print(arr1, arr1.shape)

# 升级为二维数组
arr2 = arr1.reshape((1, -1))
print(arr2, arr2.shape)

[0 1 2 3 4 5 6 7 8 9] (10,)
[[0 1 2 3 4 5 6 7 8 9]] (1, 10)


In [21]:
# 创建二维数组
arr2 = np.arange(10).reshape(2, -1)
print(arr2, arr2.shape)

# 降级为一维数组
arr1 = arr2.reshape(-1)
print(arr1, arr1.shape)


[[0 1 2 3 4]
 [5 6 7 8 9]] (2, 5)
[0 1 2 3 4 5 6 7 8 9] (10,)
