In [1]:
import numpy as np

数组的转置方法为 .T，其只对矩阵有效， 因此遇到向量要先将其转化为矩阵

In [2]:
arr1 = np.arange(1, 4)  # 创建向量
print(arr1, arr1.shape)

[1 2 3] (3,)


In [3]:
arr2 = arr1.reshape((1, -1))  # 升级为矩阵
print(arr2, arr2.shape)

[[1 2 3]] (1, 3)


In [5]:
arr3 = arr2.T  # 行矩阵的转置
print(arr3, arr3.shape)

[[1]
 [2]
 [3]] (3, 1)


In [8]:
arr1 = np.arange(3).reshape(3, 1)  # 创建列矩阵
print(arr1, arr1.shape)

arr2 = arr1.T  # 列矩阵的转置
print(arr2, arr2.shape)  # 结果为行矩阵

[[0]
 [1]
 [2]] (3, 1)
[[0 1 2]] (1, 3)


In [10]:
arr1 = np.arange(4).reshape(2, 2)  # 创建矩阵
print(arr1, arr1.shape)

arr2 = arr1.T  # 矩阵的转置
print(arr2, arr2.shape)

[[0 1]
 [2 3]] (2, 2)
[[0 2]
 [1 3]] (2, 2)


数组的翻转方法有两个，一个是上下翻转的 np.flipud( ) ，表示 up-down；
一个是左右翻转的 np.fliplr( )，表示 left-right。其中，向量只能使用 np.flipud( )，
在数学中，向量并不是横着排的，而是竖着排的

In [11]:
# 创建向量
arr1 = np.arange(10)
print(arr1)

# 翻转向量
arr_ud = np.flipud(arr1)
print(arr_ud)

[0 1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1 0]


In [14]:
# 创建矩阵
arr2 = np.arange(1, 21).reshape(4, 5)
print(arr2)

# 左右翻转
arr_lr = np.fliplr(arr2)
print(arr_lr)

# 上下翻转
arr_ud = np.flipud(arr2)
print(arr_ud)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[ 5  4  3  2  1]
 [10  9  8  7  6]
 [15 14 13 12 11]
 [20 19 18 17 16]]
[[16 17 18 19 20]
 [11 12 13 14 15]
 [ 6  7  8  9 10]
 [ 1  2  3  4  5]]


想要重塑数组的形状，需要用到 .reshape( ) 方法。
前面说过，给定了其他维度的数值，剩下一个维度可以填-1，让它自己去计
算。比如把一个 5 行 6 列的矩阵重塑为 3 行 10 列的矩阵，当列的参数 10 告诉
它，行的参数直接可以用-1 来替代，它会自己去用 30 除以 10 来计算

In [15]:
arr1 = np.arange(1, 10)  # 创建向量
print(arr1)
arr2 = arr1.reshape(3, 3)  # 变形为矩阵
print(arr2, arr2.shape)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3)


In [17]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])  # 创建矩阵
print(arr1, arr1.shape)

arr2 = arr1.reshape(6)  # 变形为向量
print(arr2, arr2.shape)

arr3 = arr1.reshape(1, 6)  # 变形为矩阵
print(arr3, arr3.shape)

[[1 2 3]
 [4 5 6]] (2, 3)
[1 2 3 4 5 6] (6,)
[[1 2 3 4 5 6]] (1, 6)


In [18]:
 # 创建向量 1
arr1 = np.array([1, 2, 3])
print(arr1)
# 创建向量 2
arr2 = np.array([4, 5, 6])
print(arr2)

# 拼接
arr3 = np.concatenate([arr1, arr2])
print(arr3, arr3.shape)

[1 2 3]
[4 5 6]
[1 2 3 4 5 6] (6,)


两个矩阵可以按不同的维度进行拼接，但拼接时必须注意维度的吻合
向量和矩阵不能进行拼接，必须先把向量升级为矩阵

In [20]:
# 创建矩阵 1
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr1)

# 创建矩阵 2
arr2 = np.array([[7, 8, 9], [10, 11, 12]])
print(arr2)

# 按第一个维度（行）拼接
arr3 = np.concatenate([arr1, arr2], axis=0)  # 默认参数 axis=0
print(arr3, arr3.shape)

# 按第二个维度（列）拼接
arr4 = np.concatenate([arr1, arr2], axis=1)
print(arr4, arr4.shape)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] (4, 3)
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]] (2, 6)


In [22]:
# 创建向量
arr = np.arange(10, 100, 10)
print(arr)

# 分裂数组 np.split( )函数中，给出的第二个参数[2,8]表示在索引[2]和索引[8]的位置截断。
arr1, arr2, arr3 = np.split(arr, [2, 8])
print(arr1)
print(arr2)
print(arr3)

[10 20 30 40 50 60 70 80 90]
[10 20]
[30 40 50 60 70 80]
[90]


In [27]:
# 创建矩阵
arr = np.arange(1, 9).reshape(2, 4)
print(arr)

# 按第一个维度（行）分裂
arr1, arr2 = np.split(arr, [1])  # 默认参数 axis=0
print(arr1, arr2)

# 按第二个维度（列）分裂
arr1, arr2, arr3 = np.split(arr, [1, 3], axis=1)
print(arr1)
print(arr2)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2 3 4]] [[5 6 7 8]]
[[1]
 [5]]
[[2 3]
 [6 7]]
