In [1]:
import numpy as np

默认情况下，NumPy 中的矩阵运算是不修改原矩阵的，操作结果会返回一个新的矩阵。
如果你希望修改原矩阵，可以使用如 +=、*= 等就地操作符，或者直接重新赋值给原矩阵

In [4]:
# 创建矩阵
arr = np.arange(1, 9).reshape(2, 4)
print(arr)

print(arr + 10)  # 加法
print(arr - 10)  # 减法
print(arr * 10)  # 乘法
print(arr / 10)  # 除法
print(arr % 10)  # 取余
print(arr ** 10)  # 平方
print(arr // 6)  # 取整

[[1 2 3 4]
 [5 6 7 8]]
[[11 12 13 14]
 [15 16 17 18]]
[[-9 -8 -7 -6]
 [-5 -4 -3 -2]]
[[10 20 30 40]
 [50 60 70 80]]
[[0.1 0.2 0.3 0.4]
 [0.5 0.6 0.7 0.8]]
[[1 2 3 4]
 [5 6 7 8]]
[[         1       1024      59049    1048576]
 [   9765625   60466176  282475249 1073741824]]
[[0 0 0 0]
 [0 1 1 1]]


同维度数组间的运算即对应元素之间的运算，这里仅以矩阵为例，向量与向
量的操作与之相同

In [5]:
# 创建矩阵
arr1 = np.arange(-1, -9, -1).reshape(2, 4)
arr2 = -arr1
print(arr1)
print(arr2)

[[-1 -2 -3 -4]
 [-5 -6 -7 -8]]
[[1 2 3 4]
 [5 6 7 8]]


In [6]:
print(arr1 + arr2)  # 加法
print(arr1 - arr2)  # 减法
print(arr1 * arr2)  # 乘法

[[0 0 0 0]
 [0 0 0 0]]
[[ -2  -4  -6  -8]
 [-10 -12 -14 -16]]
[[ -1  -4  -9 -16]
 [-25 -36 -49 -64]]


不同形状的数组之间的运算有以下规则：
⚫ 如果是向量与矩阵之间做运算，向量自动升级为行矩阵；
⚫ 如果某矩阵是行矩阵或列矩阵，则其被广播，以适配另一个矩阵的形状。

当一个形状为(x,y)的矩阵与一个向量做运算时， 要求该向量的形状必须为 y，
运算时向量会自动升级成形状为(1,y)的行矩阵，该形状为(1,y)的行矩阵再自动被
广播为形状为(x,y)的矩阵，这样就与另一个矩阵的形状适配了

In [7]:
# 向量
arr1 = np.array([-100, 0, 100])
print(arr1, arr1.shape)

[-100    0  100] (3,)


In [8]:
# 矩阵
arr2 = np.random.random((10, 3))
print(arr2, arr2.shape)

[[0.22357154 0.90927012 0.86651132]
 [0.11374156 0.52154963 0.56323807]
 [0.80330269 0.6766744  0.27934905]
 [0.31816944 0.37020358 0.38335417]
 [0.98541641 0.78289046 0.25817223]
 [0.90744532 0.30488035 0.1995808 ]
 [0.44698665 0.87479707 0.20863892]
 [0.34354711 0.56507966 0.29826657]
 [0.00215094 0.5346773  0.57684389]
 [0.35867022 0.19693622 0.84917095]] (10, 3)


In [9]:
 # 广播
print(arr1 + arr2)

[[-99.77642846   0.90927012 100.86651132]
 [-99.88625844   0.52154963 100.56323807]
 [-99.19669731   0.6766744  100.27934905]
 [-99.68183056   0.37020358 100.38335417]
 [-99.01458359   0.78289046 100.25817223]
 [-99.09255468   0.30488035 100.1995808 ]
 [-99.55301335   0.87479707 100.20863892]
 [-99.65645289   0.56507966 100.29826657]
 [-99.99784906   0.5346773  100.57684389]
 [-99.64132978   0.19693622 100.84917095]]


当一个形状为(x,y)的矩阵与一个列矩阵做运算时，要求该列矩阵的形状必须
为(x,1)，该形状为(x,1)的列矩阵再自动被广播为形状为(x,y)的矩阵，这样就与另
一个矩阵的形状适配了

In [10]:
# 列矩阵
arr1 = np.arange(3).reshape(3, 1)
print(arr1)

# 矩阵
arr2 = np.ones((3, 5))
print(arr2)

[[0]
 [1]
 [2]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [11]:
# 广播
print(arr1 * arr2)

[[0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]]


当一个形状为(1,y)的行矩阵与一个形状为(x,1) 的列矩阵做运算时， 这俩矩阵
都会被自动广播为形状为(x,y)的矩阵，这样就互相适配了

In [14]:
# 向量
arr1 = np.arange(3)
print(arr1, arr1.shape)

# 列矩阵
arr2 = np.arange(3).reshape(3, 1)
print(arr2, arr2.shape)

[0 1 2] (3,)
[[0]
 [1]
 [2]] (3, 1)


In [15]:
# 广播
print(arr1 * arr2)

[[0 0 0]
 [0 1 2]
 [0 2 4]]
