In [1]:
import numpy as np

In [3]:
# 创建向量
arr1 = np.arange(1, 10)
print(arr1)

# 访问元素
print(arr1[3])  # 正着访问
print(arr1[-1])  # 倒着访问

# 修改数组元素
arr1[3] = 100
print(arr1)

[1 2 3 4 5 6 7 8 9]
4
9
[  1   2   3 100   5   6   7   8   9]


In [5]:
# 创建矩阵
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2)

# 访问元素
print(arr2[0, 2])
print(arr2[1, -2])

# 修改元素
arr2[1, 1] = 100.9
print(arr2)

[[1 2 3]
 [4 5 6]]
3
5
[[  1   2   3]
 [  4 100   6]]


In [6]:
 # 创建向量
arr1 = np.arange(0, 90, 10)
print(arr1)

# 花式索引 普通索引用一层中括号，花式索引用两层中括号
print(arr1[[0, 2]])

[ 0 10 20 30 40 50 60 70 80]
[ 0 20]


In [8]:
# 创建矩阵
arr2 = np.arange(1, 17).reshape(4, 4)
print(arr2)

# 花式索引
print(arr2[[0, 1], [0, 1]])  # (x1,x2) (y1,y2)
print(arr2[[0, 1, 2], [2, 1, 0]])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[1 6]
[3 6 9]


In [11]:
arr1 = np.arange(10)

print(arr1)
print(arr1[1: 4])  # 从索引[1]开始，切到索引[4]之前 左闭右开
print(arr1[1:])  # 从索引[1]开始，切到结尾
print(arr1[: 4])  # 从数组开头开始，切到索引[4]之前

print(arr1)
print(arr1[2: -2])  # 切除开头 2个和结尾 2个
print(arr1[2:])  # 切除开头 2个
print(arr1[: -2])  # 切除结尾 2个

[0 1 2 3 4 5 6 7 8 9]
[1 2 3]
[1 2 3 4 5 6 7 8 9]
[0 1 2 3]
[0 1 2 3 4 5 6 7 8 9]
[2 3 4 5 6 7]
[2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7]


In [12]:
print(arr1)
print(arr1[:: 2])  # 每 2个元素采样一次
print(arr1[:: 3])  # 每 3个元素采样一次
print(arr1[1: -1: 2])  # 切除一头一尾后，每 2个元素采样一次

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]
[0 3 6 9]
[1 3 5 7]


In [14]:
arr2 = np.arange(1, 21).reshape(4, 5)
print(arr2)

# 1:3 表示行的范围，从第 1 行开始（索引为 1），到第 3 行结束
# 1:-1 表示列的范围，从第 1 列开始（索引为 1），到倒数第 1 列结束（不包括倒数第 1 列本身）。
print(arr2[1:3, 1:-1])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[ 7  8  9]
 [12 13 14]]


In [16]:
# ::3 表示行的步长为 3，意味着从第 0 行开始，每隔 3 行取一次
# ::2 表示列的步长为 2，意味着从第 0 列开始，每隔 2 列取一次
print(arr2[::3, ::2])  # 跳跃采样

[[ 1  3  5]
 [16 18 20]]


In [18]:
arr3 = np.arange(1, 21).reshape(4, 5)
print(arr3)

print(arr3[2, :])  # 提取第 2 行
print(arr3[1:3, :])  # 提取 1至 2行

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[11 12 13 14 15]
[[ 6  7  8  9 10]
 [11 12 13 14 15]]


In [19]:
print(arr3[2, :])  # 规范的提取行
print(arr3[2])  # 简便的提取行

[11 12 13 14 15]
[11 12 13 14 15]


In [20]:
arr4 = np.arange(1, 21).reshape(4, 5)
print(arr4)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [24]:
print(arr4[:, 2])  # 提取第 2列（注意，输出的是向量）
print(arr4[:, 1:3])  # 提取 1 至2 列

[ 3  8 13 18]
[[ 2  3]
 [ 7  8]
 [12 13]
 [17 18]]


In [25]:
arr5 = np.arange(1, 16).reshape(3, 5)
print(arr5)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [26]:
cut = arr5[:, 2]  # 提取第 2列为向量
print(cut)

[ 3  8 13]


In [27]:
cut = cut.reshape((-1, 1))  # 升级为列矩阵
print(cut)

[[ 3]
 [ 8]
 [13]]


In [28]:
arr = np.arange(10)  # 创建原数组 arr
print(arr)

[0 1 2 3 4 5 6 7 8 9]


与 Python 列表和 Matlab 不同，NumPy 数组的切片仅仅是原数组的一个视
图。换言之，NumPy 切片并不会创建新的变量

In [31]:
cut = arr[: 3]  # 创建 arr 的切片 cut
print(cut)

cut[0] = 100  # 对切片的数值进行修改
print(cut)
print(arr)  # 原数组也被修改

[100   1   2]
[100   1   2]
[100   1   2   3   4   5   6   7   8   9]


如果真的需要为切片创建新变量（这种情况很稀少），使用 .copy( ) 方法。

In [33]:
arr = np.arange(10)  # 创建一个 0到 10 的向量 arr
print(arr)

copy = arr[: 3].copy()  # 创建 arr 的拷贝切片
print(copy)

copy[0] = 100  # 对拷贝切片的数值进行修改
print(copy)
print(arr)  # 原数组不为所动

[0 1 2 3 4 5 6 7 8 9]
[0 1 2]
[100   1   2]
[0 1 2 3 4 5 6 7 8 9]


与 NumPy 数组的切片一样，NumPy 数组完整的赋值给另一个数组，也只是
绑定。换言之，NumPy 数组之间的赋值并不会创建新的变量，示例如下。

In [34]:
arr1 = np.arange(10)  # 创建一个 0 到10 的数组变量 arr
print(arr1)
arr2 = arr1  # 把数组 1 赋值给另一个数组 2
print(arr2)
arr2[0] = 100  # 修改数组 2
print(arr2)
print(arr1)  # 原数组也被修改

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[100   1   2   3   4   5   6   7   8   9]
[100   1   2   3   4   5   6   7   8   9]


如果真的需要赋给一个新数组，使用 .copy( ) 方法

In [35]:
arr1 = np.arange(10)  # 创建一个 0 到10 的数组变量 arr
print(arr1)
arr2 = arr1.copy()  # 把数组 1 的拷贝赋值给另一个数组 2
print(arr2)
arr2[0] = 100  # 修改数组 2
print(arr2)
print(arr1)  # 查看数组 1

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[100   1   2   3   4   5   6   7   8   9]
[0 1 2 3 4 5 6 7 8 9]
