In [1]:
import numpy as np

当矩阵乘积中混有向量时， 根据需求， 其可充当行矩阵，也可充当列矩阵，
但混有向量时输出结果必为向量

In [2]:
# 创建向量
arr1 = np.arange(5)
arr2 = np.arange(5)
print(arr1)
print(arr2)

[0 1 2 3 4]
[0 1 2 3 4]


In [3]:
# 矩阵乘积
print(np.dot(arr1, arr2))

30


In [4]:
# 创建数组
arr1 = np.arange(5)
arr2 = np.arange(15).reshape(5, 3)
print(arr1, arr1.shape)
print(arr2)

[0 1 2 3 4] (5,)
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [7]:
# 矩阵乘积
print(np.dot(arr1, arr2))

[ 90 100 110]


In [8]:
# 创建矩阵 1
arr1 = np.arange(10).reshape(5, 2)
print(arr1)

# 创建矩阵 2
arr2 = np.arange(16).reshape(2, 8)
print(arr2)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]


In [9]:
# 矩阵乘积
print(np.dot(arr1, arr2).shape)

(5, 8)


In [10]:
# 绝对值函数
arr_v = np.array([-10, 0, 10])
abs_v = np.abs(arr_v)
print('原数组是：', arr_v)
print('绝对值是：', abs_v)

原数组是： [-10   0  10]
绝对值是： [10  0 10]


In [11]:
# 三角函数
theta = np.arange(3) * np.pi / 2
sin_v = np.sin(theta)
cos_v = np.cos(theta)
tan_v = np.tan(theta)
print('原数组是：', theta)
print('正弦值是：', sin_v)
print('余弦值是：', cos_v)
print('正切值是：', tan_v)

原数组是： [0.         1.57079633 3.14159265]
正弦值是： [0.0000000e+00 1.0000000e+00 1.2246468e-16]
余弦值是： [ 1.000000e+00  6.123234e-17 -1.000000e+00]
正切值是： [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [12]:
# 指数函数
x = np.arange(1, 4)
print('x =', x)
print('e^x =', np.exp(x))
print('2^x =', 2 ** x)
print('10^x = ', 10 ** x)

x = [1 2 3]
e^x = [ 2.71828183  7.3890561  20.08553692]
2^x = [2 4 8]
10^x =  [  10  100 1000]


In [13]:
# 对数函数
x = np.array([1, 10, 100, 1000])
print('x =', x)
print('ln(x) =', np.log(x))
print('log2(x) =', np.log(x) / np.log(2))
print('log10(x) =', np.log(x) / np.log(10))

x = [   1   10  100 1000]
ln(x) = [0.         2.30258509 4.60517019 6.90775528]
log2(x) = [0.         3.32192809 6.64385619 9.96578428]
log10(x) = [0. 1. 2. 3.]


聚合很有用，这里用矩阵演示。向量与之一致，但没有 axis 参数

In [15]:
# 最大值函数 np.max( )与最小值函数 np.min( )
arr = np.random.random((2, 3))
print(arr)
print('按维度一求最大值：', np.max(arr, axis=0))  # 每一列的最大值
print('按维度二求最大值：', np.max(arr, axis=1))  # 每一行的最大值
print('整体求最大值：', np.max(arr))

[[0.75044872 0.39337807 0.66271635]
 [0.454357   0.99187685 0.15454709]]
按维度一求最大值： [0.75044872 0.99187685 0.66271635]
按维度二求最大值： [0.75044872 0.99187685]
整体求最大值： 0.991876847999946


In [16]:
 # 求和函数 np.sum( )与求积函数 np.prod( )
arr = np.arange(10).reshape(2, 5)
print(arr)
print('按维度一求和：', np.sum(arr, axis=0))
print('按维度二求和：', np.sum(arr, axis=1))
print('整体求和：', np.sum(arr))

[[0 1 2 3 4]
 [5 6 7 8 9]]
按维度一求和： [ 5  7  9 11 13]
按维度二求和： [10 35]
整体求和： 45


In [17]:
 # 均值函数 np.mean( )与标准差函数 np.std( )
arr = np.arange(10).reshape(2, 5)
print(arr)
print('按维度一求平均：', np.mean(arr, axis=0))
print('按维度二求平均：', np.mean(arr, axis=1))
print('整体求平均：', np.mean(arr))

[[0 1 2 3 4]
 [5 6 7 8 9]]
按维度一求平均： [2.5 3.5 4.5 5.5 6.5]
按维度二求平均： [2. 7.]
整体求平均： 4.5
