In [1]:
import numpy as np

In [3]:
 # 创建一维数组——向量
arr1 = np.array([1, 2, 3])
print(arr1, arr1.shape)

# 创建二维数组——行矩阵
arr2 = np.array([[1, 2, 3]])
print(arr2, arr2.shape)

# 创建二维数组——列矩阵
arr3 = np.array([[1], [2], [3]])
print(arr3, arr3.shape)

# 创建二维数组——矩阵
arr4 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr4, arr4.shape)

[1 2 3] (3,)
[[1 2 3]] (1, 3)
[[1]
 [2]
 [3]] (3, 1)
[[1 2 3]
 [4 5 6]] (2, 3)


In [4]:
 # 递增数组
arr1 = np.arange(10)  # 从 0 开始，到 10 之前结束
print(arr1)

# 递增数组
arr2 = np.arange(10, 20)  # 从 10 开始，到 20 之前结束
print(arr2)

# 递增数组
arr3 = np.arange(1, 21, 2)  # 从 1 开始，到 21 之前结束，步长为 2
print(arr3)

[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19]
[ 1  3  5  7  9 11 13 15 17 19]


In [5]:
# 全0 数组
arr1 = np.zeros(3)  # 形状为 3 的向量
print(arr1, arr1.shape)

# 全1 数组
arr2 = np.ones((1, 3))  # 形状为(1,3)的矩阵
print(arr2, arr2.shape)

# 全3.14 数组
arr3 = 3.14 * np.ones((2, 3))  # 形状为(2,3)的矩阵
print(arr3, arr3.shape)

[0. 0. 0.] (3,)
[[1. 1. 1.]] (1, 3)
[[3.14 3.14 3.14]
 [3.14 3.14 3.14]] (2, 3)


In [8]:
# 0-1 均匀分布的浮点型随机数组
arr1 = np.random.random(5)  # 形状为 5 的向量
print(arr1, arr1.shape)

# 整数型随机数组 该函数需要额外输入范围参数，本例中范围是 10-100
arr2 = np.random.randint(10, 100, (1, 15))  # 形状为(1,15)的矩阵
print(arr2, arr2.shape)

# 服从正态分布的随机数组 该函数需要额外输入正态参数，本例中均值为 0、标准差为 1
arr3 = np.random.normal(0, 1, (2, 3))  # 形状为(2,3)的二维矩阵
print(arr3)

[0.40928669 0.82204806 0.8440986  0.48540414 0.97113736] (5,)
[[21 41 38 93 51 70 22 59 48 27 41 93 21 34 42]] (1, 15)
[[-1.12977587  0.68606797 -1.04367014]
 [ 0.6093846   0.87752385 -0.57143442]]
